name: quickcoat
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  supabase_flutter: ^2.10.0
  image_picker: ^1.2.0
  smooth_page_indicator: ^1.2.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  water_drop_nav_bar: ^2.2.2
  carousel_slider: ^5.1.1
  file_picker: ^10.3.3
  video_player: ^2.10.0
  chewie: ^1.13.0
  get_storage: ^2.1.1
  lottie: ^3.3.0
  uuid: ^4.5.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/qclogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/car.png
    - assets/images/motorcycle.png
    - assets/images/bicycle.png
    - assets/images/tricycle.png
    - assets/videos/video.mp4
    - assets/animations/paymentsuccessful.json
    - assets/psgc/psgc.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
